services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPENSEARCH_SECURITY_DEMO=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    healthcheck:
      test:
        - CMD-SHELL
        - bash -lc 'curl -sk -u admin:"$OPENSEARCH_INITIAL_ADMIN_PASSWORD" https://localhost:9200/_cluster/health | grep -q "\"status\":\"green\"\|\"status\":\"yellow\""'
      interval: 10s
      timeout: 5s
      retries: 30

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPENSEARCH_SECURITY_ENABLED=true
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
      - SERVER_HOST=0.0.0.0
      - OPENSEARCH_REQUEST_TIMEOUT=90000
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "5601:5601"
